from django.db import models

from account.models import User


class App(models.Model):
    title = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='media/icons/')
    description = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    # The App must be verified throw admin users
    is_verified = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    # Link and Key now is static
    # TODO App key must be generated by some other api
    link = models.URLField()
    key = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)


class Purchase(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    link = models.URLField()
    key = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    purchase_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['owner', 'app'], name='unique_properties')
        ]